name: flake8

on:
  push:
    branches: [ master ]
  pull_request:
jobs:
  # --- code style check by flake8 ---
  flake8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    # use both MDO Lab standard config
    - name: Code style (flake8)
      run: |
        pip install flake8
        python -m flake8 mphys --count --show-source --statistics
